[package]
name = "flash-attn"
version = "0.1.0"
edition = "2024"
default-run = "flash-attn"

[workspace]

[dependencies]
cuda-device = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "20a56163f258e09f2c51e4c27ae4e4ff17582443" }
cuda-host = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "20a56163f258e09f2c51e4c27ae4e4ff17582443" }
cuda-core = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "20a56163f258e09f2c51e4c27ae4e4ff17582443" }
bench-util = { path = "../bench-util" }
kittens = { package = "ferro-kittens", git = "https://github.com/feitreim/ferro-kittens", rev = "3ae07a84671c4a19baafe5f0c720aaf63a544a88", features = ["host"] }

[profile.release]
debug = false
lto = true
