[package]
name = "ops"
version = "0.1.0"
edition = "2024"
default-run = "ops"

[workspace]

[dependencies]
cuda-device = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "20a56163f258e09f2c51e4c27ae4e4ff17582443" }
cuda-host = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "20a56163f258e09f2c51e4c27ae4e4ff17582443" }
cuda-core = { git = "https://github.com/NVlabs/cuda-oxide.git", rev = "20a56163f258e09f2c51e4c27ae4e4ff17582443" }
tensor-core = { path = "../../crates/tensor-core" }
tensor-cpu = { path = "../../crates/tensor-cpu" }
nn = { path = "../../crates/nn" }
bench-util = { path = "../bench-util" }
kittens = { package = "ferro-kittens", git = "https://github.com/feitreim/ferro-kittens", rev = "caa60756c4bf96a836a4e42c1a843408d3c7271b" }

[profile.release]
debug = false
lto = true
